{% set name = "openinference-instrumentation-langchain" %}
{% set version = "0.1.23" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/openinference_instrumentation_langchain-{{ version }}.tar.gz
  sha256: f856676814ef1dbe4b476102972648252ec396c8e494deb5442e522ccc6075ff

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8,<3.12
    - hatchling
    - pip
  run:
    - python >=3.8,<3.12
    - opentelemetry-api
    - opentelemetry-instrumentation
    - opentelemetry-semantic-conventions
    - openinference-instrumentation >=0.1.7
    - openinference-semantic-conventions >=0.1.3
    - wrapt

test:
  imports:
    - openinference.instrumentation.langchain

about:
  summary: OpenInference LangChain Instrumentation
  home: https://github.com/Arize-ai/openinference
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - michaelschiff
    - mikeldking
    - RogerHYang
    - axiomofjoy
    - anticorrelator
