{% set name = "openinference-instrumentation-langchain" %}
{% set version = "0.1.58" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/openinference_instrumentation_langchain-{{ version }}.tar.gz
  sha256: 36a1b1ad162c4e356bd28257173ee3171ad7788a96089553512c6288fa9a0f1c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }},<3.15
    - opentelemetry-api
    - opentelemetry-instrumentation
    - opentelemetry-semantic-conventions
    - openinference-instrumentation >=0.1.27
    - openinference-semantic-conventions >=0.1.17
    - wrapt

test:
  requires:
    - python {{ python_min }}
  imports:
    - openinference.instrumentation.langchain

about:
  summary: OpenInference LangChain Instrumentation
  home: https://github.com/Arize-ai/openinference
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - michaelschiff
    - mikeldking
    - RogerHYang
    - axiomofjoy
    - anticorrelator
